version: "3.8"

services:
  lightningd:
    image: vincenzopalazzo/clightning4j-node:v0.11.2
    volumes:
      - ./data:/home/clightning4j
    network_mode: "host"
    command:
      --network=testnet
      --alias=clighting4j-node
      --rgb=f07178
      --disable-plugin=bcli
      --log-level=debug
      --grpc-port=8001
      --bind-addr=127.0.0.1:9734
      --proxy=127.0.0.1:9050
      --addr=statictor:127.0.0.1:9051
      --plugin=/opt/btcli4j.sh
      --log-file=/home/clightning4j/.lightning/log.log
      --rpc-file-mode=0777
      --daemon
  grpc_test:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: "host"
    depends_on:
      - lightningd
    volumes:
      - ./data/.lightning:/.lightning
